# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.provision :shell, :path => "../../puppet/puppet.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus   = 1
  end

  config.vm.define "client1" do |client1|
     client1.vm.box = "chef/centos-6.5"
     client1.vm.network "private_network", ip: "10.2.2.2"
       
     client1.vm.provision "puppet" do |puppet|
       puppet.manifests_path = "../../puppet/manifests"
       puppet.manifest_file  = "mysql.pp"
     end
  end
  
  #config.vm.provision :shell, :path => "bootstrap.sh"  
  #config.vm.provision :puppet
  
  #config.vm.define "client2" do |client2|
  #   client2.vm.box = "chef/centos-6.5"
  #   client2.vm.network "private_network", ip: "10.2.2.4"
  #end
 
end
