# -*- mode: ruby -*-
# vi: set ft=ruby :

####
## Constants to for this OS
####
require_relative "../init.rb"
include Constants

VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  ############################################################################                  
  #####################           Global Configs         #####################
  ############################################################################ 

  ####
  ## OS for all VMs
  ####

  config.vm.box = VARGRANT_BOX


  ####
  ## Script for installing puppet on Vms
  ####

  config.vm.provision :shell, :path => PUPPET_INSTALL_SCRIPT


  ####
  ## Init modules for all VMs
  ## Will be executed BEFORE any other manifests
  ####

  config.vm.provision "puppet" do |puppet|
    puppet.module_path   = PUPPET_MODULE_PATH
    puppet.manifest_file = "default.pp"
  end


  ####
  ## Memory usage for the Vms
  ####

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus   = 1
  end

  ############################################################################                  
  ########################          VM Configs         #######################
  ############################################################################    

  ####
  ## web server
  ####

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "10.2.2.2"
    web.vm.network "forwarded_port", guest: "80", host: "8888", host_ip: "127.0.0.1"

    web.vm.provision "puppet" do |puppet|
      puppet.module_path   = PUPPET_MODULE_PATH
      puppet.manifest_file = "web.pp"
    end
  end

  ####
  ## master server
  ####

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "10.2.2.4"
    master.vm.network "forwarded_port", guest: "3306", host: "1028", host_ip: "127.0.0.1"

    master.vm.provision "puppet" do |puppet|
      puppet.module_path   = PUPPET_MODULE_PATH
      puppet.manifest_file = "mysql-master.pp"
    end
  end


  ####
  ## slave servers
  ####

  config.vm.define "slave1" do |slave1|
    slave1.vm.network "private_network", ip: "10.2.2.6"

    slave1.vm.provision "puppet" do |puppet|
      puppet.module_path   = PUPPET_MODULE_PATH
      puppet.manifest_file = "mysql-slave1.pp"
    end
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.network "private_network", ip: "10.2.2.8"

    slave2.vm.provision "puppet" do |puppet|
      puppet.module_path   = PUPPET_MODULE_PATH
      puppet.manifest_file = "mysql-slave2.pp"
    end
  end
  
  config.vm.define "slave3" do |slave3|
    slave3.vm.network "private_network", ip: "10.2.2.10"

    slave3.vm.provision "puppet" do |puppet|
      puppet.module_path   = PUPPET_MODULE_PATH
      puppet.manifest_file = "mysql-slave3.pp"
    end
  end
  
end
