# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

############################################################################                  
#####################          Editable Variables      #####################
############################################################################ 

VAGRANTFILE_API_VERSION = "2"

VARGRANT_BOX            = "chef/centos-6.5"
PUPPET_INSTALL_SCRIPT   = "../../puppet/puppet.sh"
PUPPET_MODULE_PATH      = "../../puppet/modules"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  ############################################################################                  
  #####################           Global Configs         #####################
  ############################################################################ 

  ####
  ## OS for all VMs
  ####

  config.vm.box = VARGRANT_BOX


  ####
  ## Script for installing puppet on Vms
  ####

  config.vm.provision :shell, :path => PUPPET_INSTALL_SCRIPT


  ####
  ## Global puppet for all VMs
  ####

  config.vm.provision "puppet" do |puppet|
    puppet.module_path = PUPPET_MODULE_PATH
    puppet.manifest_file = "global.pp"
  end


  ####
  ## Memory usage for the Vms
  ####

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus   = 1
  end

  ############################################################################                  
  ########################          VM Configs         #######################
  ############################################################################    

  ####
  ## master server
  ####

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "10.2.2.2"
  end


  ####
  ## slave servers
  ####

  config.vm.define "slave1" do |slave1|
    slave1.vm.network "private_network", ip: "10.2.2.4"
  end
  
end
