# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "master" do |master|
     master.vm.box = "chef/centos-6.5"
     #master.vm.provision :shell, :path => "bootstrap.sh"
     master.vm.network "private_network", ip: "10.2.2.2"
     #master.vm.synced_folder "mnt/", "/mnt", disabled: true
     #master.ssh.username = "swift"
     #master.ssh.private_key_path = "/home/swift/.ssh/id_rsa"
     #master.ssh.password = "p"
  end
  
  config.vm.define "slave" do |slave|
     slave.vm.box = "chef/centos-6.5"
     #slave.vm.provision :shell, :path => "bootstrap.sh"
     slave.vm.network "private_network", ip: "10.2.2.4"
     #slave.vm.synced_folder "mnt/", "/mnt", disabled: true
     #slave.ssh.username = "swift"
     #slave.ssh.password = "p"
  end
   
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus   = 1
  end

  #config.vm.define "master" do |master|
  #   master.vm.box = "chef/centos-6.5"
  #   master.vm.network "private_network", ip: "10.2.2.2"
  #end
  
  #config.vm.define "slave" do |slave|
  #   slave.vm.box = "chef/centos-6.5"
  #   slave.vm.network "private_network", ip: "10.2.2.4"
  #end
 
  #config.vm.synced_folder "mnt/", "/mnt", disabled: true

end
