# -*- mode: ruby -*-
# vi: set ft=ruby :

####
## Constants to for this OS
####
require_relative "../init.rb"
include Constants

VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  ############################################################################                  
  #####################           Global Configs         #####################
  ############################################################################ 

  ####
  ## OS for all VMs
  ####

  config.vm.box = VARGRANT_BOX


  ####
  ## Script for installing puppet on Vms
  ####

  config.vm.provision :shell, :path => PUPPET_INSTALL_SCRIPT
  

  ####
  ## Init modules for all VMs
  ## Will be executed BEFORE any other manifests
  ####

  config.vm.provision "puppet" do |puppet|
    puppet.module_path   = PUPPET_MODULE_PATH
    puppet.manifest_file = "default.pp"
  end

  ####
  ## Set location of synced folder
  ####

  # config.vm.synced_folder "shared/", "/var/shared"

  ####
  ## Memory usage for the Vms
  ####

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus   = 1
  end

  ############################################################################                  
  ########################          VM Configs         #######################
  ############################################################################    

  ####
  ## web server
  ####
  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "10.2.2.2"
    master.vm.network "forwarded_port", guest: "15672", host: "1028", host_ip: "127.0.0.1"
    master.vm.network "forwarded_port", guest: "5672", host: "1029", host_ip: "127.0.0.1"

    master.vm.provision "puppet" do |puppet|
      puppet.module_path   = PUPPET_MODULE_PATH
      puppet.manifest_file = "server.pp"
    end
  end

  config.vm.define "slave1" do |slave1|
    slave1.vm.network "private_network", ip: "10.2.2.4"

    slave1.vm.provision "puppet" do |puppet|
      puppet.module_path   = PUPPET_MODULE_PATH
      puppet.manifest_file = "server.pp"
    end
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.network "private_network", ip: "10.2.2.6"

    slave2.vm.provision "puppet" do |puppet|
      puppet.module_path   = PUPPET_MODULE_PATH
      puppet.manifest_file = "server.pp"
    end
  end

end
